### ISSUE TITLE
feat: allow user to create tags for stamps

### ISSUE THREAD

**Issue by significance** [ethersphere/swarm-cli#360] opened 2022-04-08 08:31 UTC
when creating a stamp, add a human readable tag so that it's easy to remember which stamp is for which purpose

display this tag in the 'select a stamp' dialogue as well as the `stamp ls` output

**Comment by AuHau** [comment] 2022-04-08 09:03
Duplicate of https://github.com/ethersphere/swarm-cli/issues/342 which is closed now ;-)

**Closed by AuHau** 2022-04-08 09:03 UTC
Labels: issue
