### ISSUE TITLE
pss message send failed

### ISSUE THREAD

**Issue by zhupengxiang** [ethersphere/swarm-cli#135] opened 2021-06-07 07:44 UTC
![image](https://user-images.githubusercontent.com/17894209/120978623-41108680-c7a7-11eb-896d-6dceff0d0c82.png)

**Comment by Cafe137** [comment] 2021-06-07 09:11
Hello @zhupengxiang!

Your Bee node replies with an Internal Server Error without further information available in the response.

I suggest you to check your Bee node log - there may be something useful there. 😉

**Comment by zhupengxiang** [comment] 2021-06-07 09:15
Where is the Bee node log

**Comment by Cafe137** [comment] 2021-06-07 09:57
@zhupengxiang Are you running Bee on Windows? Did you use Docker, or plain install?

Linux & MacOS:

https://docs.ethswarm.org/docs/working-with-bee/logs-and-files/

Windows:

> In Windows, the logs are simply written to stdout.  If you didn't redirect that to a file, then the logs will be limited to what you can scroll back in your command prompt window.

**Comment by zhupengxiang** [comment] 2021-06-08 04:18
![image](https://user-images.githubusercontent.com/17894209/121122146-7e325280-c853-11eb-94ec-b218c21cc1e2.png)

The log has no information about the error report when calling the api

**Comment by agazso** [comment] 2021-06-08 09:20
Related issue https://github.com/ethersphere/bee/issues/2026

**Comment by Cafe137** [comment] 2021-06-09 07:58
@zhupengxiang Is there anything else I can help with from `swarm-cli` side? As the root cause of this issue is tracked in Bee, I propose to close this issue otherwise.

**Closed** 2021-06-10 06:23 UTC
Labels: issue
